name: Deploy to AWS

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Build Docker image
      run: |
        docker build -t hra-app ./docker
        docker tag hra-app:latest <account_id>.dkr.ecr.us-east-1.amazonaws.com/hra-app

    - name: Login to ECR
      run: aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin <account_id>.dkr.ecr.us-east-1.amazonaws.com

    - name: Push image to ECR
      run: |
        docker push <account_id>.dkr.ecr.us-east-1.amazonaws.com/hra-app

    - name: Terraform Apply
      run: |
        cd terraform
        terraform init
        terraform apply -auto-approve -var="ecr_image_url=<account_id>.dkr.ecr.us-east-1.amazonaws.com/hra-app"
