name: Deploy to AWS ECR

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Login to ECR
      run: |
        aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 195074685960.dkr.ecr.us-east-1.amazonaws.com

    - name: Build Docker image
      run: |
        docker build -t hra-app -f docker/Dockerfile .
        docker tag hra-app:latest 195074685960.dkr.ecr.us-east-1.amazonaws.com/hra-app:latest
        docker push 195074685960.dkr.ecr.us-east-1.amazonaws.com/hra-app:latest

    - name: Push image to ECR
      run: |
        docker push 195074685960.dkr.ecr.us-east-1.amazonaws.com/hra-app

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Terraform Apply
      run: |
        cd terraform
        terraform init
        terraform apply -auto-approve -var="ecr_image_url=<195074685960.dkr.ecr.us-east-1.amazonaws.com/hra-app"
